### ISSUE TITLE
NullPointerException with Hwyla and some machines

### ISSUE THREAD

**Issue by frank89722** [Trinsdar/GTC-Expansion#10]
**Description of the Bug**
After I install Hwyla game will crash when I look at  Distillation Tower and Fluid castor

**To Reproduce**

1. run this mod with hwyla
2. looking at Distillation Tower or some block from GTCX have fluid container that placed in the world
3. game crashed

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: I think we don't need this..?

 - Crash report (If available): https://paste.dimdev.org/lorobesiki.mccrash

**Additional context**

I found a similar issue [here ](https://github.com/BluSunrize/ImmersiveEngineering/issues/2766) it maybe helpful

**Comment by e99999** [comment]
@frank89722 what happens when you look at other GTC/GTCX machines, like the GTC drum for instance? just wondering if this is with any IC2 Tank or specifically those two machines you listed from Expansion.

**Comment by frank89722** [comment]
I have tested IC2 and GTC blocks with fluid container are all fine, but GTCX blocks with fluid container all crash like that, not only that two machines.

**Comment by Trinsdar** [comment]
posting a crash I think is relevent since the dimdev site is down: https://gist.github.com/Trinsdar/a2471d1ab1db91f4dc3a108767e35256

**Comment by Trinsdar** [comment]
going to close this since I think I have long since fixed this
