### ISSUE TITLE
mekanism compat

### ISSUE THREAD

**Issue by DbpGaming** [Trinsdar/GTC-Expansion#14]
**Is your feature request related to a problem? Please describe.**
in gt4 there was mekanism compat for ore processing, it's just kinda annoying that it's not here

**Describe the solution you'd like**
- in gt4, all mekanism dirty dust centrifuges as if it was impure, you dont have impure dusts in GTCX, but you have all the outputs, so this compat should be easy recreatable
image: https://cdn.discordapp.com/attachments/422478424637177856/688766913978958082/unknown.png
- in addition, mekanism enriched iron dust, should probably be interchangeable with refined iron, as it's basically the same thing
image: https://cdn.discordapp.com/attachments/422478424637177856/688766537816866853/unknown.png

**Additional context**
you can use theis oredict to not have to hard dep mekanism, but still have the centrifuge compat, there isn't a enriched iron oredict, so that would probably have to hard dep
- dustDirtyMaterial (material being whatever material say iron) for the dirty dust centrifuging

**Comment by Trinsdar** [comment]
going to comment that I did add a sort of non-compat: you can't use mek osmium in gt recipes, my recipes require OsmiumGT

**Comment by Trinsdar** [comment]
ok I've decided to not bother, imo mek dirty dust isn't really the same, and with mek being so op, I don't even like it anyways, so I don't want to spend time adding compat for this when I could do other shit like finishing pipes and other shit
