### ISSUE TITLE
overpowered weapons

### ISSUE THREAD

**Issue by DbpGaming** [Trinsdar/GTC-Expansion#15]
**Description of the Bug**
all GTCX tools are extremely overpowered in terms of damage values

**To Reproduce**
1. use gtcx
2. use any sword, or look at their tooltip

**Expected behavior**

sapphire/ruby are 8.5 damage, diamond is 7, the steel sword is the same as diamond, way less durability sure but way cheaper to, and tungstensteel, is 2x of diamond, and is encroaching on the nanosaber, the axes, pickaxes, and shovels have the same issue, in GT4, steel was the same damage as iron, tungstensteel was the same  damage as diamond, i don't see why all of these are way more powerful, i can only name 4 swords more powerful than this tungstensteel, in all of 1.12 modded

**Screenshots & Video**
N/A

**Logs & Environment**
N/A

**Additional context**
 i'd prefer tungstensteel to do like 8 or 9 i never understood what the point when it was the same as diamond, but this is just to much, i think 8 or 9 would really be the sweet spot, for steel probably 6.5, ruby/sapphire probably 7 so the same as diamond, for the swords, for the axes i would say do something similar, but i haven't thought about what they should all be yet

**Comment by Trinsdar** [comment]
ok steel will be 6.5, ruby and sapphire will be 7, and for tungstensteel I was thinking 10. as for the axes, the damage is dynamically calculated, I think axes are always sword damage + 2, well except for vanilla it seems
