### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/GTC-Expansion#2]
![image](https://user-images.githubusercontent.com/25727222/67091465-56413780-f1b5-11e9-8fcb-d3c409b69eb6.png)

Mods: 
Forge: 2838
IC2C: 1.5.4.5
GTC: 1.0.4
GTC_E: 0.0.2.2 

log: https://hastebin.com/vilukikaka.sql

EDIT: Sometimes machines are localized as "Air"

**Comment by Trinsdar** [comment]
Alrrafy has been fixed in dev. Will be in the nect release

**Comment by CrossVas** [comment]
Good to know. 
Waiting for next release. Thanks!

**Comment by Trinsdar** [comment]
New version is out.
