### ISSUE TITLE
Connected textures for machine casings?

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Trinsdar/GTC-Expansion#20]
**Is your feature request related to a problem? Please describe.**
GT2 to GT4 had these neat connected textures for machine casings and (iridium reinforced) tungstensteel blocks. Upcoming boiler's face textures will look way better with them.

**Describe the solution you'd like**
Connected texture for machine casings and iridium reinforced tungstensteel block just like in GT2-GT4 (as well as texture override for tungstensteel block if possible)
![2020-04-23_08 20 08](https://user-images.githubusercontent.com/5104603/80062454-783cbd80-853c-11ea-83b5-2ee8d9d53e34.png)

**Additional context**
CTM doesn't work with IC2C's sprite replacement system so i don't think it's possible to replicate them with resource packs or in any other way outside the mod's code.

**Comment by Trinsdar** [comment]
Currently i don't really know how to get connected textures working with the sprite system, but once i finish with the turbine texture compat, it might be easier to figure out.

**Comment by Trinsdar** [comment]
this has been finished for a while, forgot to close this
