### ISSUE TITLE
Distillation Tower unable to accept fluids. 

### ISSUE THREAD

**Issue by Sk11ppy** [Trinsdar/GTC-Expansion#21]
I'm running GTC Expansion 0.1.1, and I am unable to insert fluids into the distillery.  I have tried inserting fluids into every side, and have configured the sides to import to no avail.  The slots inside the GUI are greyed out as well.  Am I doing something wrong, or is it bugged?

**Comment by Trinsdar** [comment]
you should be able to insert fluids into the left and top sides

**Comment by Trinsdar** [comment]
I can't seem to be able to reproduce the issue, are you trying to insert a fluid that doesn't have a recipe?

**Comment by Sk11ppy** [comment]
So upon further testing I managed to get Crude oil into the Distillation tower, but for some reason I still cannot get naphtha in.  I noticed that I do not have a bucket for naphtha, only tubes and canisters.  Could this be the reason?  Maybe some fluid dictionary conflict?

**Comment by Trinsdar** [comment]
depends, what naptha is it? gtc or thermal? as the fluid name should be directly `naphtha`

**Comment by Sk11ppy** [comment]
It's gtc naphtha.  I can right click on the distillery with a tube of oil to fill it, but naphtha doesn't work.  I've also tried piping it in, which doesn't work either.

**Comment by Trinsdar** [comment]
ok found the problem and fixed it. I had simply forgot to add naptha to the list
