### ISSUE TITLE
IC2C Extras recipes compat issues

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Trinsdar/GTC-Expansion#23]
**Description of the Bug**
Only LV machines from IC2CE (except 1 which doesn't!) has recipe overrides with oredicted machine blocks.

**Expected behavior**
All machines from IC2CE having recipe overrides with oredicted machine blocks.

**Screenshots & Video**
![javaw_2020-05-30_19-53-35](https://user-images.githubusercontent.com/5104603/83334614-61625700-a2b0-11ea-8fb2-ed2750c0266d.png)
![javaw_2020-05-30_20-02-02](https://user-images.githubusercontent.com/5104603/83334625-74752700-a2b0-11ea-8e78-389666c2083e.png)
![javaw_2020-05-30_20-02-07](https://user-images.githubusercontent.com/5104603/83334626-75a65400-a2b0-11ea-90b5-757a3dfdb344.png)

**Logs & Environment**
IC2C 1.12-1.5.4.5
IC2CExtras 1.4.4.12
GTClassic 1.1.4
GTCExpansion 0.1.1

**Additional context**
This actually could be handled in IC2CE itself, by checking the existence of machine blocks OD values.

**Comment by Trinsdar** [comment]
Yah, i'll probably fix this in ic2c extras. Don't worry about moving the issue, as they are both my mods, so it doesn't really matter

**Comment by Trinsdar** [comment]
Fixed in Ic2c extras, which will have a new version out once I re-balance nuclear cell stuff again so it fits into gtcx well
