### ISSUE TITLE
Extend upgrade slot amount to 4 to match GTC

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#24]
**Is your feature request related to a problem? Please describe.**

![javaw_2f0J9wV8E8](https://user-images.githubusercontent.com/6339511/83354794-3990f300-a385-11ea-9aad-9bfd11e97da1.png)
![javaw_4x5Ee8CPQw](https://user-images.githubusercontent.com/6339511/83354796-3b5ab680-a385-11ea-8fa1-52bab9208bcd.png)
![javaw_TTwhpVpIDG](https://user-images.githubusercontent.com/6339511/83354822-69d89180-a385-11ea-9709-c447958e2ab6.png)

**Describe the solution you'd like**

I get 4 upgrade slots in each GTCX machine, like in IC2C and GTC (maybe except blast furnace, since 2 upgrade slots there seems to be fair to me)

--------------------

Keep in mind that while regular machines in IC2C have 4 upgrade slots, overclocked ones do have only 2 slots for upgrades, so i might be missing point in only 2 upgrade slots in GTCX machines

![javaw_ibh8CF00Rj](https://user-images.githubusercontent.com/6339511/83354856-b328e100-a385-11ea-96f6-86f1fd3ffff0.png)
![javaw_lMmGJMKFk6](https://user-images.githubusercontent.com/6339511/83354857-b45a0e00-a385-11ea-8eca-5a89a32f1173.png)

**Comment by Trinsdar** [comment]
The electrolyzer is a tier 2 machine, so therefore it only gets 2 slots. If i have missed any tier 1 machines that only have 2 slots, i'll fix them and make them have , but tier 2 only get 2 slots

**Comment by DBotThePony** [comment]
Okay, i'll reopen if i find any.

**Comment by DBotThePony** [comment]
![javaw_xtee2e7m9K](https://user-images.githubusercontent.com/6339511/83843687-be865e80-a72f-11ea-8b88-0e9535483d3c.png)
![javaw_WxnSaXIYVS](https://user-images.githubusercontent.com/6339511/83843689-bf1ef500-a72f-11ea-8e45-b80632b194fe.png)

is this something that should be addressed?

**Comment by Trinsdar** [comment]
Hm maybe, though I'm not sure with multiblocks.

**Comment by CrossVas** [comment]
I think that multiblock machines shouldn't have upgrade slots at all. Maybe they should have them only for some types of upgrades (for item/fluid manipulation upgrades for instance). Maybe...

**Comment by Trinsdar** [comment]
I can actually limit what type of  upgrades they can use
