### ISSUE TITLE
GTCX can not be compiled locally

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#25]
**Description of the Bug**

GTCX can not be compiled locally because curseforge has weird/broken cloudflare firewall setup (for several months already) where `I'm Under Attack!` cover even API endpoints for maven (in fact, curseforge even blocked most of search bots by utilizing cloudflare firewall rules wrong)

**To Reproduce**

1. Clear gradle build cache from required libraries to build GTCX
2. Try to build it
3.
```
15:36:26.471 [INFO] [org.gradle.internal.resource.transport.http.HttpClientHelper] Failed to get resource: GET. [HTTP HTTP/1.1 503 Service Temporarily Unavailable: https://minecraft.curseforge.com/api/maven/CraftTweaker2/ZenScript/maven-metadata.xml]
15:36:26.472 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Download https://minecraft.curseforge.com/api/maven/CraftTweaker2/ZenScript/maven-metadata.xml'
15:36:26.472 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Download https://minecraft.curseforge.com/api/maven/CraftTweaker2/ZenScript/maven-metadata.xml' completed
```

**Comment by Trinsdar** [comment]
Try removing the curseforge maven under repositories and tell me if that fixes it

**Comment by DBotThePony** [comment]
It managed to resolve dependencies without curseforge maven but failed to compile because you do not require gtclassic in `dependencies {}` gradle.build file
![pwsh_M2kuxtOOMc](https://user-images.githubusercontent.com/6339511/83355650-f89bdd00-a38a-11ea-8ba8-62fc1850e255.png)

**Comment by Trinsdar** [comment]
Oh that's cause i use a deobsficated version of gtc in libs, cause i need things not yet in the curseforge release. 
Edit: removed a dumb rant
