### ISSUE TITLE
Chromite never spawn due to missing worldgen entry

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#26]
I legit excavated two 256x256 areas using quarry to only find this

https://github.com/Trinsdar/GTC-Expansion/blob/49951898bdc0a76f2c55f86dcbf379f4fe22d081/src/main/java/gtc_expansion/GTCXWorldGen.java#L23-L28

Now chromite search will haunt me in my dreams

**Comment by YuRaNnNzZZ** [comment]
![javaw_2020-06-02_16-55-28](https://user-images.githubusercontent.com/5104603/83528531-e12b3400-a4f1-11ea-834b-7e856121437a.png)

**Comment by Trinsdar** [comment]
Oh woops

**Comment by Trinsdar** [comment]
Fixed in dev
