### ISSUE TITLE
Strange behavior of Chemical Reactor with empty Fluid Tubes

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Trinsdar/GTC-Expansion#27]
**Description of the Bug**
Sulfuric Acid recipe lists two tubes of water and one empty tube in it's NEI recipe. But reactor only checks for the first two tubes and third one can be with any fluid in it.

**To Reproduce**
1. Open chemical reactor
2. Place 1 sulfur dust, two tubes with water and third tube with any liquid in it
3. Watch as chemical reactor processes the recipe as usual

**Expected behavior**
Empty cells should be checked if they're actually empty?

**Screenshots & Video**
![javaw_2020-06-03_01-57-25](https://user-images.githubusercontent.com/5104603/83577932-2e34f780-a53e-11ea-91f8-6367561f5f93.png)
![javaw_2020-06-03_01-57-39](https://user-images.githubusercontent.com/5104603/83577942-312fe800-a53e-11ea-8474-46edd92681b7.png)
![javaw_2020-06-03_01-57-47](https://user-images.githubusercontent.com/5104603/83577950-342ad880-a53e-11ea-8a10-bcdcdefe7d0d.png)
![javaw_2020-06-03_01-57-55](https://user-images.githubusercontent.com/5104603/83577956-3725c900-a53e-11ea-894b-70235dca12cc.png)

**Logs & Environment**
GTC: 1.1.4, GTCX: 0.1.1

**Comment by Trinsdar** [comment]
ok that is really weird

**Comment by Trinsdar** [comment]
ok turns out this happens in the centrifuge too, so might be a gtclassic issue

**Comment by DbpGaming** [comment]
isn't this just the recipe system assuming no nbt means any nbt?

**Comment by Trinsdar** [comment]
yah most likely

**Comment by Trinsdar** [comment]
might be an ic2 thing

**Comment by Trinsdar** [comment]
closing this cause there isn't really any way to fix this, and plus this will be pretty much obsolete next release
