### ISSUE TITLE
Overlapping PESU recipe

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#28]
**Description of the Bug**

![javaw_hL6yTxSVcj](https://user-images.githubusercontent.com/6339511/83589652-665c2a80-a57e-11ea-9f55-d9e437fb6fb0.png)
![javaw_x07xoEMswe](https://user-images.githubusercontent.com/6339511/83589655-678d5780-a57e-11ea-9491-879311f98f4a.png)
![javaw_JAEBSB02Fd](https://user-images.githubusercontent.com/6339511/83589658-6825ee00-a57e-11ea-8284-2cbb5d3b2dee.png)

**Environment**
 - Mod version: 0.1.1
 - Forge: Build 2854

**Comment by Trinsdar** [comment]
oops. just going to remove the third recipe

**Comment by DBotThePony** [comment]
Fixed via https://github.com/Trinsdar/GTC-Expansion/commit/51577cf4aac0239b40aaad10e8c8a223617061ee
