### ISSUE TITLE
Latest git revision does not have fusion reactor JEI recipes

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#29]
**Description of the Bug**

Shift + R in NEI keyboard layout (U in JEI keyboard layout) on fusion reactor
![javaw_kqGW4y0P46](https://user-images.githubusercontent.com/6339511/84345252-195c0200-abd7-11ea-88ff-04126b446ea0.png)

This button does nothing
![javaw_hI1W2KvlPK](https://user-images.githubusercontent.com/6339511/84345346-56c08f80-abd7-11ea-9844-b4a87d6aaa3d.png)

**Comment by Trinsdar** [comment]
that's because I have the stuff commented out, as I haven't used the latest gtc in my enviorment yet.

**Comment by Trinsdar** [comment]
I'm waiting for it to be released on curseforge
