### ISSUE TITLE
[Suggestion] Make GTC_E to use old "legacy" multiblock structures. 

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/GTC-Expansion#3]
Why did you decide to make GT2 multiblock machines to look like GT5 one in GTC_E? 
It would be great to have a configurable option to use legacy GT2-style multiblock structures for all machines (Industrial Blast Furnace, Industrial Grinder, etc.) 

![image](https://user-images.githubusercontent.com/25727222/67104898-7cc09c00-f1d0-11e9-8667-f05d5f053b17.png)
![image](https://user-images.githubusercontent.com/25727222/67104950-919d2f80-f1d0-11e9-801e-fdc132d16364.png)

Thank you!

**Comment by Trinsdar** [comment]
I did it that way because I personally prefer the multiblocks to not be popped out. I could add a config option; the only problem is I would have to make duplicate gui textures for the multiblocks. Also because of how the system works, it wouldn't be possible to use the same structure for more then one controller, just as an fyi

**Comment by CrossVas** [comment]
I proposed to do so not because of the ability to connect more than 1 controller block, but in order to be able to automate somehow these machines. In GT5 we have 1 input and 1 output block and the controller itself, so the player can easily access the I/O ports of the multiblock machine. 

In GTC_E we have only one side of the block for: Energy, Input, Output.

**Comment by DbpGaming** [comment]
in GTC/GTCEX, all sides of a multiblock should allow energy, input, and output, if its not it has to be a bug

**Comment by Trinsdar** [comment]
Yah the casings will eventually allow items and fluids, but they don't currently  they already allow energy and opening the gui from the casings

**Comment by Trinsdar** [comment]
Also i wasn't saying that the controller outside the casings was for connecting more then one structure block; i was just letting you know that it wouldn't be possible if i do do the gt2 structure config

**Comment by Trinsdar** [comment]
Ok decided to do legacy style gt multiblocks as doing any sort of item or fluid importing and exporting through the casings is too complex for me right now

**Comment by e99999** [comment]
> Ok decided to do legacy style gt multiblocks as doing any sort of item or fluid importing and exporting through the casings is too complex for me right now

For anyone following this topic the remaining GTC multi blocks (mainly just fusion) also reflect this for consistency , until a full item/fluid/energy system can be implemented through multi block casings
