### ISSUE TITLE
Large steam turbine can not be assembled?

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#32]
**Description of the Bug**

I tried various configurations and none of them worked
![2020-06-11_12 03 57](https://user-images.githubusercontent.com/6339511/84347071-cfc1e600-abdb-11ea-8a5c-58e20df89be3.png)
![2020-06-11_12 03 59](https://user-images.githubusercontent.com/6339511/84347074-d18ba980-abdb-11ea-8fb8-9016f470d8fb.png)
![2020-06-11_12 04 10](https://user-images.githubusercontent.com/6339511/84347078-d3556d00-abdb-11ea-96bf-30f60911c3bd.png)
![2020-06-11_12 04 12](https://user-images.githubusercontent.com/6339511/84347080-d51f3080-abdb-11ea-961f-917f60cad5ed.png)

However, after seeing this
https://github.com/Trinsdar/GTC-Expansion/blob/c9943d962562f9dd640833f238abb0e6954ce804/src/main/java/gtc_expansion/tile/multi/GTCXTileMultiLargeSteamTurbine.java#L303

And this
https://github.com/Trinsdar/GTC-Expansion/blob/c9943d962562f9dd640833f238abb0e6954ce804/src/main/java/gtc_expansion/tile/multi/GTCXTileMultiLargeSteamTurbine.java#L312

I started to question myself if it is ever possible to construct such turbine

*checkStructure() { return lorem ipsum; }*

**Comment by Trinsdar** [comment]
It should work fine, i tested this myself, and i would know if tge structure didn't work. Did you build it like what's here in the wiki for gt4?
https://ftbwiki.org/Large_Steam_Turbine_(GregTech_4_Structure)
Ignore the output and maintenance hatch stuff, output will invalidate the structure and maintenance doesn't exist

**Comment by DBotThePony** [comment]
Output hatch were causing the problem. But you really should allow output hatches (they don't serve any purpose (unless you add water recycling from steam for realism), but in general they should not invalidate the structure, like in gt5 and original gt4)

**Comment by Trinsdar** [comment]
I'll consider it
