### ISSUE TITLE
Double Ram usage in large modpack with Version 0.1.2

### ISSUE THREAD

**Issue by RheyvenFox** [Trinsdar/GTC-Expansion#36]
**Description of the Bug**
I have a rather large Modpack that I have put together, and when running version 0.1.2 of GTC-E it causes both the server and client instance to use almost the entire 8gb of ram allocated to the instance. When I roll back to 0.1.1 it is reduced to half the memory usage. I'm not sure this is a bug or if this is just due to the larger amount of items included in 0.1.2

**To Reproduce**

Load the Modpack I have with 0.1.2 enabled. Run the instance and watch ram usage stay very high. 

**Expected behavior**
I expect it to not us as much ram. 

**Screenshots & Video**
With version 0.1.1 loaded:
https://i.imgur.com/hHteLMW.png
With version 0.1.2 loaded:
https://i.imgur.com/sLsiD6v.png
Modpack List(Best way I could think to do it):
https://puu.sh/Gmmn6/66c55b6efe.png

**Logs & Environment**
I only have the latest.log files. I have added these below. Since they are over 512kb both Github and pastebin didn't like them. So I have uploaded them as text documents to my website. 
 - Full log: 
Log for running Ver 0.1.2
https://www.dolinmyster.com/LogFilever0.1.2.txt
Log for running Ver 0.1.1
https://www.dolinmyster.com/LogFilever0.1.1.txt
Not 
 - Crash report (If available): 
It doesn't crash, if anything it just causes a bunch of lag when the ram usage slowly climbs over 8gb.

**Additional context**
If these are the wrong log files, please let me know. I will get the correct ones.

**Comment by Trinsdar** [comment]
Yah it was an issue, i already resolved it in dev, at least most of it. There may be a couple more small improvements, but nothing more big

**Comment by Trinsdar** [comment]
It was actually related to blockstates, specifically connected textures using blockstates instead of doing a custom model

**Comment by Trinsdar** [comment]
I'm going to leave this open till i release 0.2

**Comment by RheyvenFox** [comment]
Thanks for the quick response! I do know it was not as high when I was running it on just IC2 Classic, GTC, and GTCX. So wasn't sure if it was a mod conflict or just how things were loading. Look forward to the next update!

**Comment by Trinsdar** [comment]
almost forgot, 0.2 is out, hopefully it at least helps with most of it
