### ISSUE TITLE
Large Steam Turbine bugs

### ISSUE THREAD

**Issue by Erik3003** [Trinsdar/GTC-Expansion#37]
**Description of the Bug**

The large steam turbine doesn't output water to the output hatch. Another small thing that might be considered a bug is that the large steam turbine stops working when the energy buffer is full, voiding the excess electricity would be a better idea imo, to prevent reactor meltdowns because of energy storage running full.

**To Reproduce**

1. Build large steam turbine with output hatch
2. Pump steam into it
3. Look into output hatch

**Expected behavior**

Water should appear in the output hatch.

**Screenshots & Video**

None.

**Logs & Environment**

 - Full log: https://pastebin.com/vu6BAhjy

 - Crash report (If available): None

**Additional context**

None.

**Comment by Trinsdar** [comment]
Ok i'll check out the bug. As for the voiding energy thing, i don't think so, i don't want to be cruel, all they have to do is setup redstone that turns the reactor off when energy gets above 50% or something in a connected power storage block.

**Comment by Trinsdar** [comment]
Ok fixed
