### ISSUE TITLE
[Bug] GUI Bug 

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/GTC-Expansion#4]
Found a small bug with Assembling Machine. 
When you put some upgrades in the first upper slot, it appears also in "battery slot" as if they copy each other. The second slot below works as intended.

GTC_E: 0.0.3.

![GUI](https://user-images.githubusercontent.com/25727222/67523251-f9fb7d80-f6b6-11e9-81ae-fb0e2a1c1ad4.gif)

**Comment by Trinsdar** [comment]
woops

**Comment by DbpGaming** [comment]
seems you start the upgrade slot on slot 4 which is the same as your fuel slot, am i correct?

**Comment by Trinsdar** [comment]
yes I already figured it was that

**Comment by Trinsdar** [comment]
ok fixed in dev
