### ISSUE TITLE
Crafting table single use batteries recipe.

### ISSUE THREAD

**Issue by sscards55** [Trinsdar/GTC-Expansion#48]
Batteries crafted in the crafting table contain no charge. When the batteries are crafted they contain no tags, which also causes them to not be usable in the extractor. Using craftweakers hand command, I noticed that they had no energy tag.

Battery that was spawned in with creative and depleted:
<gtc_expansion:acid_battery>.withTag({charge: 0.0 as float})

Battery that was crafted in the crafting table:
<gtc_expansion:acid_battery>.withTag({})

**Comment by Trinsdar** [comment]
Already fixed this in dev

**Comment by sscards55** [comment]
Alright, that was quick.

**Comment by Trinsdar** [comment]
yah that was cause I found it a week ago or so
