### ISSUE TITLE
Axes' attack speed is too high

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Trinsdar/GTC-Expansion#5]
6.5 for Flint Axe and up to 14 with Tungstensteel Axe, isn't that a bit too OP?
![](https://yurie.thigh-high.club/70zsgp8l.png)

Here's the vanilla diamond axe for comparison:
![](https://yurie.thigh-high.club/hzleb0nu.png)

**Comment by DbpGaming** [comment]
the increase from iron to diamond on attack speed is 0.1, all of your axes are fast enough they seem to completely circumvent the combat update

edit: i remember the testing server had classic combat on, probably part of the reason these issues exist, may need to start testing without stuff like that more

**Comment by Trinsdar** [comment]
it is definitely too high
