### ISSUE TITLE
gregtech classic for 1.7.10

### ISSUE THREAD

**Issue by GabrielitoPL** [Trinsdar/GTC-Expansion#51]
Greetings, I would like to know if there is a possibility that this gregtech 4 mod is for version 1.7.10. for IC2 Classic, because there is none for this version and it is only for the experimental version that I personally don't like, there is a possibility, I know there is a gregtech 6 but I like 4 more.

**Comment by Trinsdar** [comment]
sorry, but I'm not touching 1.7, however if people want to port the mod themselves then prs are always welcome
