### ISSUE TITLE
Crash on start MC.

### ISSUE THREAD

**Issue by Pilad** [Trinsdar/GTC-Expansion#6]
**Description of the Bug**
Crash on start MC.

**To Reproduce**

1. Place block '...'
3. See '...'

**Expected behavior**

**Screenshots & Video**

**Logs & Environment**

 - Full log: 

 - Crash report (If available): 
https://pastebin.com/QnieFu1z

**Additional context**

**Comment by Trinsdar** [comment]
can you try this version and see if it fixes it? I don't have time to test right now.
https://send.firefox.com/download/e26b9c7fa6002e8a/#9JWAJXgBsjQJ50X0qkeBiA

**Comment by Pilad** [comment]
Checked. Downloading the game was successful. The game does not seem to throw. I will continue to test.

**Comment by Trinsdar** [comment]
I'll be releasing a build on curseforge today
