### ISSUE TITLE
Feature Request From CrossVas 

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/GTC-Expansion#9]
**Is your feature request related to a problem? Please describe.**
I love GTCX and all the stuff it contains, but playing with this mod makes me feel a bit bored because of some aspects. 
1. All GTCX Tools (Wrench, Hammer, File) are "infinite". What do I mean? Well let's say you have a fresh world, you have done some mining and you want to get started with GTC and GTCX. The first thing you will craft is Iron Hammer in order to make plates, then Iron Wrench and File. After a while you will find out that there are no reasons to upgrade to Bronze, and then to steel, tungstensteel, because iron tools you made have enough durability and they are cheaper (just do some mining, find iron and that's it!)
Shortly: The player doesn't have stimuli to upgrade to Bronze, Steel, Tungsten Steel tools.
2. Some items have two recipes (one of which is useless). I.e. Drill, Saw and all IC2C' tools, Empty Cells.

**Describe the solution you'd like**
1. 
- In order to make the player use advanced tools (>Iron Tools), it would be great to decrease the durability to be: 128, 256, 512, 5120.
- Make Wrenches and Hammers take damage more than 1 when crafting Machine Hull, etc..

2.
- Have a config option to enable/disable "hard recipes". 

If there's something that I'm missing, let me know.

EDIT: If GTCX is meant not to be hard, sorry and skip this.

Thanks,
CrossVas.

**Comment by e99999** [comment]
I like these ideas, pushing people into machining instead of trivial and easy crafting. I also have advocated for hammers needing to be the proper tier to be used, so you couldnt use a bronze hammer to make tungstensteel plates

**Comment by CrossVas** [comment]
Closing as it isn't needed anymore.
